const Menu =[
    {
    id: 1,
    image: "images/maggie.jpg",
    name: "maggie",
    category: "Breakfast",
    price: "₹ 100",
    description: "Chotu Ka Dhaba's Maggie is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 2,
    image: "images/appey.jpg",
    name: "Appey",
    category: "Breakfast",
    price: "₹ 300",
    description: "Chotu Ka Dhaba's Appey is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends."
},
{
    id: 3,
    image: "images/upma.jpeg",
    name: "Upma",
    category: "Breakfast",
    price: "₹ 200",
    description: "Chotu Ka Dhaba's Upma is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 4,
    image: "images/poha.jpg",
    name: "Poha",
    category: "Breakfast",
    price: "₹ 100",
    description: "Chotu Ka Dhaba's Poha is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 5,
    image: "images/idli.jpg",
    name: "Idli",
    category: "Breakfast",
    price: "₹ 200",
    description: "Chotu Ka Dhaba's Idli is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 6,
    image: "images/aaluParatha.jpg",
    name: "Aalu Paratha",
    category: "Breakfast",
    price: "₹ 200",
    description: "Chotu Ka Dhaba's Aalu Paratha is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 7,
    image: "images/dosa.png",
    name: "Dosa",
    category: "Lunch",
    price: "₹ 300",
    description: "Chotu Ka Dhaba's Dosa is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 8,
    image: "images/rajma chawal.jpg",
    name: "Rajma Chawal",
    category: "Lunch",
    price: "₹ 300",
    description: "Chotu Ka Dhaba's Rajma Chawal is delicious. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},

{
    id: 9,
    image: "images/paneeer naan.jpg",
    name: "Paneer & Naan",
    category: "Lunch",
    price: "₹ 500",
    description: "Chotu Ka Dhaba's Butter Paneer with Butter Naan is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 10,
    image: "images/regular thali.jpg",
    name: "Regular Thali",
    category: "Lunch",
    price: "₹ 200",
    description: "Chotu Ka Dhaba's Regular Thali is delicious. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 11,
    image: "images/special thali.jpg",
    name: "Special Thali",
    category: "Lunch",
    price: "₹ 400",
    description: "Chotu Ka Dhaba's Special Thali is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 12,
    image: "images/chinise.jpg",
    name: "Chinese",
    category: "Lunch",
    price: "₹ 500",
    description: "Chotu Ka Dhaba's Special Thali is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 13,
    image: "images/evening1.jpg",
    name: "Samosa",
    category: "Evening",
    price: "₹ 100",
    description: "Chotu Ka Dhaba's Samosa is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 14,
    image: "images/evening2.jpg",
    name: "Kachori",
    category: "Evening",
    price: "₹ 150",
    description: "Chotu Ka Dhaba's Kachori is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 15,
    image: "images/evening3.jpg",
    name: "Pakora",
    category: "Evening",
    price: "₹ 50",
    description: "Chotu Ka Dhaba's Pakora is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 16,
    image: "images/evening4.jpeg",
    name: "Noodles",
    category: "Evening",
    price: "₹ 280",
    description: "Chotu Ka Dhaba's Noodles is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 17,
    image: "images/evening5.jpeg",
    name: "Momos",
    category: "Evening",
    price: "₹ 280",
    description: "Chotu Ka Dhaba's Momos is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 18,
    image: "images/evening6.jpeg",
    name: "Pani-puri",
    category: "Evening",
    price: "₹ 180",
    description: "Chotu Ka Dhaba's Pani-puri is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 19,
    image: "images/dinner1.jpeg",
    name: "Chole Bhature",
    category: "Dinner",
    price: "₹ 480",
    description: "Chotu Ka Dhaba's Chole-Bhature is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 20,
    image: "images/dinner2.jpeg",
    name: "Pav Bhaji",
    category: "Dinner",
    price: "₹ 450",
    description: "Chotu Ka Dhaba's Pav Bhaji is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 21,
    image: "images/dinner3.jpg",
    name: "Palak Paneer",
    category: "Dinner",
    price: "₹ 550",
    description: "Chotu Ka Dhaba's Palak Paneer with Roti and leamon rice is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 22,
    image: "images/dinner4.jpg",
    name: "Puran Poli",
    category: "Dinner",
    price: "₹ 500",
    description: "Chotu Ka Dhaba's Puran Poli is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 23,
    image: "images/dinner5.jpg",
    name: "Hyderabadi Biryani",
    category: "Dinner",
    price: "₹ 300",
    description: "Chotu Ka Dhaba's Hyderabadi Veg Biryani is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
{
    id: 24,
    image: "images/special thali.jpg",
    name: "Thali",
    category: "Dinner",
    price: "₹ 400",
    description: "Chotu Ka Dhaba's Thali is awesome. It is healthy and delicious. Restaurant's environment is quite good. Please order it and enjoy with your family and friends.",
},
];

export default Menu;